[mypy]
python_version = 3.9
ignore_missing_imports = True
disable_error_code = arg-type, misc, assignment, return-value, attr-defined, name-defined, union-attr, index, operator, override, type-arg, var-annotated, return
